### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'normalized'

### ISSUE THREAD

**Issue by abecus** [macbre/sql-metadata#161]
getting error when trying to get the tables for sql below,
```
sql = """
WITH uisd_filter_table as (
    select
        session_id,
        srch_id,
        srch_ci,
        srch_co,
        srch_los,
        srch_sort_type,
        impr_list
    from
        uisd
    where
        datem <= date_sub(date_add(current_date(), 92), 7 * 52)
        and lower(srch_sort_type) in ('expertpicks', 'recommended')
        and srch_ci <= date_sub(date_add(current_date(), 92), 7 * 52)
        and srch_co >= date_sub(date_add(current_date(), 1), 7 * 52)
)
select
    DISTINCT session_id,
    srch_id,
    srch_ci,
    srch_co,
    srch_los,
    srch_sort_type,
    l.impr_property_id as expe_property_id,
    l.impr_position_across_pages
from
    uisd_filter_table lateral view explode(impr_list) table as l
"""
```

How to reproduce the error:
```
p = Parser(sql)
print(p.tables)
```

Error:
```
Traceback (most recent call last):
  File "/Users/asalam/vscode/new/source_analyser/utils.py", line 152, in <module>
    print(p.tables)
  File "/Users/asalam/Library/Python/3.8/lib/python/site-packages/sql_metadata/parser.py", line 398, in tables
    with_names = self.with_names
  File "/Users/asalam/Library/Python/3.8/lib/python/site-packages/sql_metadata/parser.py", line 544, in with_names
    if token.next_token.normalized in WITH_ENDING_KEYWORDS:
AttributeError: 'NoneType' object has no attribute 'normalized'
```

**Comment by collerek** [comment]
Created a discussio: https://github.com/macbre/sql-metadata/discussions/166

**Comment by collerek** [comment]
@macbre - I think we should either close this one and open a new one with enhancement for lateral view, or rename this one and change the labels, what do you think?

**Comment by collerek** [comment]
@abecus The original bug was resolved but the tables still will return wrong data as the lateral view explode is not yet supported.
Therefore I changed the name and label of this issue.

**Comment by collerek** [comment]
fixed in v3
